#!/bin/bash

# Example 4: Capture an opponent piece
# Execute a CAPTURE action to remove a piece and move attacker

echo "================================================"
echo "Capture a Chess Piece - CAPTURE Action"
echo "================================================"
echo ""
echo "This example demonstrates a CAPTURE move, where:"
echo "  1. An attacking piece is picked up"
echo "  2. The captured piece is removed from the board"
echo "  3. The attacker is placed on the captured piece's square"
echo ""
echo "Prerequisites:"
echo "  - Main system running (chess_system.launch.py)"
echo "  - Both attacker and target pieces must be visible"
echo "  - Target square must have an opponent piece"
echo ""
echo "Action Parameters:"
echo "  - action_type: 1 (CAPTURE)"
echo "  - piece_aruco_id: ArUco ID of attacking piece"
echo "  - target_square: Square where captured piece sits (e.g., 'D5')"
echo "  - captured_piece_aruco_id: ArUco ID of piece being captured"
echo "  - castling_side: '' (not used for CAPTURE)"
echo ""
echo "================================================"
echo ""

echo "Example 1: White pawn on E4 captures black pawn on D5"
echo ""
echo "Initial state:"
echo "  - White pawn: E4 (ArUco 305)"
echo "  - Black pawn: D5 (ArUco 204)"
echo ""
echo "Command:"
echo "  ros2 action send_goal /chess_action action_manager/action/ChessAction \\"
echo "    \"{action_type: 1, piece_aruco_id: 305, target_square: 'D5', \" \\"
echo "    \"captured_piece_aruco_id: 204, castling_side: ''}\" \\"
echo "    --feedback"
echo ""
echo "Expected behavior:"
echo "  1. Sensing: Locate white pawn at E4"
echo "  2. Sensing: Locate black pawn at D5 (for validation)"
echo "  3. Planning: Compute grasp and placement poses"
echo "  4. Motion: Approach E4 → grip white pawn → lift"
echo "  5. Motion: Move to D5 → release white pawn"
echo "  6. Action: Remove black pawn from board (Gazebo delete)"
echo "  7. Verify: Confirm white pawn at D5"
echo ""
echo "Result:"
echo "  success: true"
echo "  final_square: 'D5'"
echo ""
echo "================================================"
echo ""

echo "Example 2: Black queen captures white knight"
echo ""
echo "Scenario:"
echo "  - Black queen at D5 (ArUco 215)"
echo "  - White knight at F3 (ArUco 311)"
echo ""
echo "Command:"
echo "  ros2 action send_goal /chess_action action_manager/action/ChessAction \\"
echo "    \"{action_type: 1, piece_aruco_id: 215, target_square: 'F3', \" \\"
echo "    \"captured_piece_aruco_id: 311, castling_side: ''}\" \\"
echo "    --feedback"
echo ""
echo "================================================"
echo ""

echo "Important Notes:"
echo ""
echo "1. In Gazebo simulation, captured pieces are deleted from the world"
echo "   (they disappear from the board)"
echo ""
echo "2. In real hardware mode, you need to manually remove the"
echo "   captured piece from the board (the robot only moves the attacker)"
echo ""
echo "3. The captured piece's ArUco ID should match its current position"
echo "   for validation"
echo ""
echo "4. After capture, the board state is updated via sensing"
echo ""
echo "================================================"
