#!/bin/bash

# Example 2: Test piece location service
# Query where a specific piece is located on the board

echo "================================================"
echo "Test Piece Location Service"
echo "================================================"
echo ""
echo "This example shows how to query the location of a chess piece."
echo ""
echo "Prerequisites:"
echo "  - Main system running (chess_system.launch.py)"
echo "  - Pieces visible to the camera"
echo ""
echo "What this does:"
echo "  Queries the sensing_module to get the location of a piece"
echo "  by its ArUco marker ID"
echo ""
echo "================================================"
echo ""

echo "Example 1: Query white king (ArUco ID 316)"
echo ""
echo "Command:"
echo "  ros2 service call /piece_location sensing_module/srv/PieceLocation \\"
echo "    \"{aruco_id: 316}\""
echo ""
echo "Expected output:"
echo "  found: true"
echo "  pose:"
echo "    position:"
echo "      x: 0.0          # meters (board center = origin)"
echo "      y: -0.175       # meters (rank 1 = -175mm from center)"
echo "      z: 0.04         # meters (on board surface)"
echo "    orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}"
echo "  cell: 'E1'          # Chess notation"
echo ""
echo "================================================"
echo ""

echo "Example 2: Query black pawn on D7 (ArUco ID 204)"
echo ""
echo "Command:"
echo "  ros2 service call /piece_location sensing_module/srv/PieceLocation \\"
echo "    \"{aruco_id: 204}\""
echo ""
echo "Expected output:"
echo "  found: true"
echo "  cell: 'D7'"
echo ""
echo "================================================"
echo ""

echo "All piece marker IDs:"
echo ""
echo "Black pieces:"
echo "  Pawns:    201-208   (on ranks 2-7, files A-H)"
echo "  Rooks:    209-210   (A8, H8)"
echo "  Knights:  211-212   (B8, G8)"
echo "  Bishops:  213-214   (C8, F8)"
echo "  Queen:    215       (D8)"
echo "  King:     216       (E8)"
echo ""
echo "White pieces:"
echo "  Pawns:    301-308   (on ranks 2-7, files A-H)"
echo "  Rooks:    309-310   (A1, H1)"
echo "  Knights:  311-312   (B1, G1)"
echo "  Bishops:  313-314   (C1, F1)"
echo "  Queen:    315       (D1)"
echo "  King:     316       (E1)"
echo ""
echo "================================================"
