#!/bin/bash

# Example 3: Move a single piece
# Execute a MOVE action to relocate a piece to an empty square

echo "================================================"
echo "Move a Chess Piece - MOVE Action"
echo "================================================"
echo ""
echo "This example demonstrates how to move a piece from its"
echo "current position to a target square."
echo ""
echo "Prerequisites:"
echo "  - Main system running (chess_system.launch.py)"
echo "  - Target square must be empty"
echo ""
echo "Action Parameters:"
echo "  - action_type: 0 (MOVE)"
echo "  - piece_aruco_id: ArUco ID of piece to move"
echo "  - target_square: Destination cell (e.g., 'E4')"
echo "  - captured_piece_aruco_id: 0 (not used for MOVE)"
echo "  - castling_side: '' (not used for MOVE)"
echo ""
echo "================================================"
echo ""

echo "Example 1: Move white pawn from E2 to E4"
echo ""
echo "Command:"
echo "  ros2 action send_goal /chess_action action_manager/action/ChessAction \\"
echo "    \"{action_type: 0, piece_aruco_id: 305, target_square: 'E4', \" \\"
echo "    \"captured_piece_aruco_id: 0, castling_side: ''}\" \\"
echo "    --feedback"
echo ""
echo "Expected behavior:"
echo "  1. [10%]  Sensing: Locate pawn (find it at E2)"
echo "  2. [20%]  Planning: Compute target pose for E4"
echo "  3. [30%]  Planning: Generate pick-place trajectory"
echo "  4. [50%]  Motion: Close gripper → lift → move → open gripper"
echo "  5. [90%]  Verify: Re-sense to confirm at E4"
echo "  6. [100%] Success: Message indicates move complete"
echo ""
echo "You should see feedback messages showing progress:"
echo ""
echo "Feedback:"
echo "  progress: 10.0"
echo "  status: 'Sensing current position'"
echo "  ..."
echo "  progress: 100.0"
echo "  status: 'Move complete'"
echo ""
echo "Result:"
echo "  success: true"
echo "  message: 'Chess action completed successfully'"
echo "  final_square: 'E4'"
echo ""
echo "================================================"
echo ""

echo "Example 2: Move black knight from B8 to C6"
echo ""
echo "Command:"
echo "  ros2 action send_goal /chess_action action_manager/action/ChessAction \\"
echo "    \"{action_type: 0, piece_aruco_id: 211, target_square: 'C6', \" \\"
echo "    \"captured_piece_aruco_id: 0, castling_side: ''}\" \\"
echo "    --feedback"
echo ""
echo "================================================"
echo ""

echo "Coordinate System (Chess Notation to XYZ):"
echo ""
echo "  Cell     →  X (m)      Y (m)       Z (m)"
echo "  ----        ------     ------      ------"
echo "  A1      →  -0.175     -0.175      0.04"
echo "  E1      →   0.0       -0.175      0.04  (white king start)"
echo "  E4      →   0.0       -0.025      0.04  (common opening)"
echo "  E8      →   0.0        0.175      0.04  (black king start)"
echo "  H8      →   0.175      0.175      0.04"
echo ""
echo "  Note: Board center (origin) is at (0, 0)"
echo "        Each square is 0.05 m (5 cm)"
echo ""
echo "================================================"
